<a href="https://colab.research.google.com/github/PythonIndian/Python/blob/main/D4_66_DL_Lab_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Single Layer Perceptron**

In [ ]:
x_input=[0,1,0.5,0.2]
w_weight=[0.4,0.3,0.6]
threshold = 0.5

In [ ]:
def step(weighted_sum):
  print('final weighted sum :',weighted_sum)
  print('threshold :',threshold)
  if weighted_sum >=threshold:
    return 1
  else:
    return 0

In [ ]:
def perceptron():
  weighted_sum=0
  for x,w in zip(x_input,w_weight):
    weighted_sum+=x*w
    print('weighted_sum',weighted_sum)
  return step(weighted_sum)

In [ ]:
output = perceptron()
print("output=",output)

weighted_sum 0.0
weighted_sum 0.3
weighted_sum 0.6
final weighted sum : 0.6
threshold : 0.5
output= 1

# **Change Threshold**

In [ ]:
threshold = 0.8
perceptron()

weighted_sum 0.0
weighted_sum 0.3
weighted_sum 0.6
final weighted sum : 0.6
threshold : 0.8

0

In [ ]:
threshold = 0.2 #threshold dec
perceptron()

weighted_sum 0.0
weighted_sum 0.3
weighted_sum 0.6
final weighted sum : 0.6
threshold : 0.2

1

In [ ]:
x_input = [0.1,0.5,0.2]
w_weight = [0.3,0.1,0.2] #dec weight
threshold = 0.5
perceptron()

weighted_sum 0.03
weighted_sum 0.08
weighted_sum 0.12000000000000001
final weighted sum : 0.12000000000000001
threshold : 0.5

0

In [ ]:
x_input = [0.1,0.5,0.2]
w_weight = [0.7,0.8,0.9] #increased weight
threshold = 0.5
perceptron()

weighted_sum 0.06999999999999999
weighted_sum 0.47000000000000003
weighted_sum 0.65
final weighted sum : 0.65
threshold : 0.5

1

# **Increased weight or decreased threshold gives output == 1**

# **Titanic Dataset**

# **Data Cleaning**

In [ ]:
import pandas as pd

df = pd.read_excel("/titanic.xlsx")

print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
df.drop(['Name'],axis=1,inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Sex          891 non-null    object
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64
 6   Parch        891 non-null    int64
 7   Ticket       891 non-null    object
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    object
 10  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

In [ ]:
df.drop(['SibSp'],axis=1,inplace=True)
df.drop(['Parch'],axis=1,inplace=True)
df.drop(['Ticket'],axis=1,inplace=True)
df.drop(['Embarked'],axis=1,inplace=True)

In [ ]:
df

     PassengerId  Survived  Pclass     Sex   Age     Fare Cabin
0              1         0       3    male  22.0   7.2500   NaN
1              2         1       1  female  38.0  71.2833   C85
2              3         1       3  female  26.0   7.9250   NaN
3              4         1       1  female  35.0  53.1000  C123
4              5         0       3    male  35.0   8.0500   NaN
..           ...       ...     ...     ...   ...      ...   ...
886          887         0       2    male  27.0  13.0000   NaN
887          888         1       1  female  19.0  30.0000   B42
888          889         0       3  female   NaN  23.4500   NaN
889          890         1       1    male  26.0  30.0000  C148
890          891         0       3    male  32.0   7.7500   NaN

[891 rows x 7 columns]

In [ ]:
df.drop(['Cabin'],axis=1,inplace=True)

In [ ]:
df

     PassengerId  Survived  Pclass     Sex   Age     Fare
0              1         0       3    male  22.0   7.2500
1              2         1       1  female  38.0  71.2833
2              3         1       3  female  26.0   7.9250
3              4         1       1  female  35.0  53.1000
4              5         0       3    male  35.0   8.0500
..           ...       ...     ...     ...   ...      ...
886          887         0       2    male  27.0  13.0000
887          888         1       1  female  19.0  30.0000
888          889         0       3  female   NaN  23.4500
889          890         1       1    male  26.0  30.0000
890          891         0       3    male  32.0   7.7500

[891 rows x 6 columns]

In [ ]:
df

     PassengerId  Survived  Pclass     Sex   Age     Fare
0              1         0       3    male  22.0   7.2500
1              2         1       1  female  38.0  71.2833
2              3         1       3  female  26.0   7.9250
3              4         1       1  female  35.0  53.1000
4              5         0       3    male  35.0   8.0500
..           ...       ...     ...     ...   ...      ...
886          887         0       2    male  27.0  13.0000
887          888         1       1  female  19.0  30.0000
888          889         0       3  female   NaN  23.4500
889          890         1       1    male  26.0  30.0000
890          891         0       3    male  32.0   7.7500

[891 rows x 6 columns]

In [ ]:
df.head()

   PassengerId  Survived  Pclass     Sex   Age     Fare
0            1         0       3    male  22.0   7.2500
1            2         1       1  female  38.0  71.2833
2            3         1       3  female  26.0   7.9250
3            4         1       1  female  35.0  53.1000
4            5         0       3    male  35.0   8.0500

In [ ]:
data = df.copy()
data.drop(['Survived'],axis=1,inplace=True)
print(data)

     PassengerId  Pclass     Sex   Age     Fare
0              1       3    male  22.0   7.2500
1              2       1  female  38.0  71.2833
2              3       3  female  26.0   7.9250
3              4       1  female  35.0  53.1000
4              5       3    male  35.0   8.0500
..           ...     ...     ...   ...      ...
886          887       2    male  27.0  13.0000
887          888       1  female  19.0  30.0000
888          889       3  female   NaN  23.4500
889          890       1    male  26.0  30.0000
890          891       3    male  32.0   7.7500

[891 rows x 5 columns]

In [ ]:
data.drop(['PassengerId'],axis=1,inplace=True)

In [ ]:
data

     Pclass     Sex   Age     Fare
0         3    male  22.0   7.2500
1         1  female  38.0  71.2833
2         3  female  26.0   7.9250
3         1  female  35.0  53.1000
4         3    male  35.0   8.0500
..      ...     ...   ...      ...
886       2    male  27.0  13.0000
887       1  female  19.0  30.0000
888       3  female   NaN  23.4500
889       1    male  26.0  30.0000
890       3    male  32.0   7.7500

[891 rows x 4 columns]

In [ ]:
data.isnull()

     Pclass    Sex    Age   Fare
0     False  False  False  False
1     False  False  False  False
2     False  False  False  False
3     False  False  False  False
4     False  False  False  False
..      ...    ...    ...    ...
886   False  False  False  False
887   False  False  False  False
888   False  False   True  False
889   False  False  False  False
890   False  False  False  False

[891 rows x 4 columns]

In [ ]:
data.isnull().sum()

Pclass      0
Sex         0
Age       177
Fare        0
dtype: int64

In [ ]:
target = df.Survived
target

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [ ]:
target.isnull().sum()

0

In [ ]:
data.isnull().sum()

Pclass      0
Sex         0
Age       177
Fare        0
dtype: int64

In [ ]:
data.Age.mean()

29.69911764705882

In [ ]:
data['Age'].fillna(data.Age.mean(),inplace=True)

In [ ]:
data.isnull().sum()

Pclass    0
Sex       0
Age       0
Fare      0
dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Pclass  891 non-null    int64
 1   Sex     891 non-null    object
 2   Age     891 non-null    float64
 3   Fare    891 non-null    float64
dtypes: float64(2), int64(1), object(1)
memory usage: 28.0+ KB

In [ ]:
data['Sex'] = data['Sex'].replace(['male','female','other'],[0,1,2])

In [ ]:
data

     Pclass     Sex        Age     Fare
0         3    male  22.000000   7.2500
1         1  female  38.000000  71.2833
2         3  female  26.000000   7.9250
3         1  female  35.000000  53.1000
4         3    male  35.000000   8.0500
..      ...     ...        ...      ...
886       2    male  27.000000  13.0000
887       1  female  19.000000  30.0000
888       3  female  29.699118  23.4500
889       1    male  26.000000  30.0000
890       3    male  32.000000   7.7500

[891 rows x 4 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Pclass  891 non-null    int64
 1   Sex     891 non-null    int64
 2   Age     891 non-null    float64
 3   Fare    891 non-null    float64
dtypes: float64(2), int64(2)
memory usage: 28.0 KB

In [ ]:
data.shape #independent

(891, 4)

In [ ]:
target.shape #dependent

(891,)

# **Splitting into Training and Testing 20:80**

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(data,target,test_size=0.2) #splitted into 20:80 ratio

In [ ]:
len(X_train)

712

In [ ]:
len(X_test)

179

In [ ]:
len(y_train)

712

In [ ]:
len(y_test)

179

# **Perceptron of sklearn**

In [ ]:
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split

In [ ]:
model=Perceptron()
model.fit(X_train,y_train)
y_predict=model.predict(X_test)
print(accuracy_score(y_test,y_predict))

0.6201117318435754

# **Perceptron using AND Gate**

In [ ]:
x_input = [0,0,0,0]
w_weight = [0.4,0.3,0.6]
threshold = 0.5

In [ ]:
perceptron()

weighted_sum 0.0
weighted_sum 0.0
weighted_sum 0.0
final weighted sum : 0.0
threshold : 0.5

0

In [ ]:
x_input = [0,0,0,1]
w_weight = [0.4,0.3,0.6]
threshold = 0.5
perceptron()

weighted_sum 0.0
weighted_sum 0.0
weighted_sum 0.0
final weighted sum : 0.0
threshold : 0.5

0

In [ ]:
x_input = [0,0,1,1]
w_weight = [0.4,0.3,0.6]
threshold = 0.5
perceptron()

weighted_sum 0.0
weighted_sum 0.0
weighted_sum 0.6
final weighted sum : 0.6
threshold : 0.5

1

In [ ]:
x_input = [0,1,1,1]
w_weight = [0.4,0.3,0.6]
threshold = 0.5
perceptron()

weighted_sum 0.0
weighted_sum 0.3
weighted_sum 0.8999999999999999
final weighted sum : 0.8999999999999999
threshold : 0.5

1

In [ ]:
x_input = [1,1,1,1]
w_weight = [0.4,0.3,0.6]
threshold = 0.5
perceptron()

weighted_sum 0.4
weighted_sum 0.7
weighted_sum 1.2999999999999998
final weighted sum : 1.2999999999999998
threshold : 0.5

1

In [ ]:
# importing Python library
import numpy as np

# define Unit Step Function
def unitStep(v):
	if v >= 0:
		return 1
	else:
		return 0

# design Perceptron Model
def perceptronModel(x, w, b):
	v = np.dot(w, x) + b
	y = unitStep(v)
	return y

# AND Logic Function
# w1 = 1, w2 = 1, b = -1.5
def AND_logicFunction(x):
	w = np.array([1, 1])
	b = -1.5
	return perceptronModel(x, w, b)

# testing the Perceptron Model
test1 = np.array([0, 1])
test2 = np.array([1, 1])
test3 = np.array([0, 0])
test4 = np.array([1, 0])

print("AND({}, {}) = {}".format(0, 1, AND_logicFunction(test1)))
print("AND({}, {}) = {}".format(1, 1, AND_logicFunction(test2)))
print("AND({}, {}) = {}".format(0, 0, AND_logicFunction(test3)))
print("AND({}, {}) = {}".format(1, 0, AND_logicFunction(test4)))

AND(0, 1) = 0
AND(1, 1) = 1
AND(0, 0) = 0
AND(1, 0) = 0